
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int NUMERO = 52;
  public static final int SHORT = 8;
  public static final int POR = 35;
  public static final int CHAR = 4;
  public static final int EQUALS = 51;
  public static final int CASE = 24;
  public static final int DOUBLE = 54;
  public static final int RESTA = 31;
  public static final int PRIVATE = 10;
  public static final int CONTINUE = 26;
  public static final int OOR = 39;
  public static final int INT = 2;
  public static final int FOR = 20;
  public static final int OPENPAR = 55;
  public static final int STATIC = 29;
  public static final int SEMICOLON = 48;
  public static final int IDENTIFICADOR = 46;
  public static final int NOT = 45;
  public static final int MENORIGUAL = 42;
  public static final int AND = 36;
  public static final int OR = 37;
  public static final int CLASS = 12;
  public static final int DIV = 33;
  public static final int IF = 27;
  public static final int CLOSEPAR = 56;
  public static final int DOT = 47;
  public static final int MAYORIGUAL = 44;
  public static final int DECIMAL = 53;
  public static final int EOF = 0;
  public static final int BOOLEAN = 17;
  public static final int RETURN = 18;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int COMA = 50;
  public static final int CADENA = 40;
  public static final int MENOS = 32;
  public static final int MENOR = 41;
  public static final int MOD = 34;
  public static final int BREAK = 19;
  public static final int VOID = 14;
  public static final int SWITCH = 23;
  public static final int BYTE = 5;
  public static final int MAYOR = 43;
  public static final int IMPORT = 15;
  public static final int COLON = 49;
  public static final int ELSE = 28;
  public static final int PROTECTED = 11;
  public static final int FINAL = 16;
  public static final int WHILE = 21;
  public static final int CLOSEBRACE = 58;
  public static final int DEFAULT = 25;
  public static final int FLOAT = 6;
  public static final int PUBLIC = 9;
  public static final int OPENBRACE = 57;
  public static final int LONG = 7;
  public static final int STRING = 3;
  public static final int DO = 22;
  public static final int AAND = 38;
  public static final int MAS = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "STRING",
  "CHAR",
  "BYTE",
  "FLOAT",
  "LONG",
  "SHORT",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "CLASS",
  "NEW",
  "VOID",
  "IMPORT",
  "FINAL",
  "BOOLEAN",
  "RETURN",
  "BREAK",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "CONTINUE",
  "IF",
  "ELSE",
  "STATIC",
  "MAS",
  "RESTA",
  "MENOS",
  "DIV",
  "MOD",
  "POR",
  "AND",
  "OR",
  "AAND",
  "OOR",
  "CADENA",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "NOT",
  "IDENTIFICADOR",
  "DOT",
  "SEMICOLON",
  "COLON",
  "COMA",
  "EQUALS",
  "NUMERO",
  "DECIMAL",
  "DOUBLE",
  "OPENPAR",
  "CLOSEPAR",
  "OPENBRACE",
  "CLOSEBRACE"
  };
}

