
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JParser;

/** CUP generated class containing symbol constants. */
public class JSONParserSym {
  /* terminals */
  public static final int CLOSEBRACE = 16;
  public static final int CADENA = 19;
  public static final int OPENBRACE = 15;
  public static final int METODOS = 5;
  public static final int DECIMAL = 21;
  public static final int SCORE = 3;
  public static final int COLON = 13;
  public static final int TIPO = 8;
  public static final int VARIABLES = 4;
  public static final int COMA = 14;
  public static final int COMENTARIOS = 6;
  public static final int NOMBRE = 7;
  public static final int EOF = 0;
  public static final int PARAMETROS = 10;
  public static final int COMILLA = 22;
  public static final int TEXTO = 11;
  public static final int NUMERO = 20;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 18;
  public static final int OPENBRACKET = 17;
  public static final int IDENTIFICADOR = 12;
  public static final int CLASES = 2;
  public static final int FUNCION = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASES",
  "SCORE",
  "VARIABLES",
  "METODOS",
  "COMENTARIOS",
  "NOMBRE",
  "TIPO",
  "FUNCION",
  "PARAMETROS",
  "TEXTO",
  "IDENTIFICADOR",
  "COLON",
  "COMA",
  "OPENBRACE",
  "CLOSEBRACE",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "CADENA",
  "NUMERO",
  "DECIMAL",
  "COMILLA"
  };
}

